 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/assembleia", type: :request do
  # Assembleium. As you add validations to Assembleium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Assembleium.create! valid_attributes
      get assembleia_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      assembleium = Assembleium.create! valid_attributes
      get assembleium_url(assembleium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_assembleium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      assembleium = Assembleium.create! valid_attributes
      get edit_assembleium_url(assembleium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Assembleium" do
        expect {
          post assembleia_url, params: { assembleium: valid_attributes }
        }.to change(Assembleium, :count).by(1)
      end

      it "redirects to the created assembleium" do
        post assembleia_url, params: { assembleium: valid_attributes }
        expect(response).to redirect_to(assembleium_url(Assembleium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Assembleium" do
        expect {
          post assembleia_url, params: { assembleium: invalid_attributes }
        }.to change(Assembleium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post assembleia_url, params: { assembleium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested assembleium" do
        assembleium = Assembleium.create! valid_attributes
        patch assembleium_url(assembleium), params: { assembleium: new_attributes }
        assembleium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the assembleium" do
        assembleium = Assembleium.create! valid_attributes
        patch assembleium_url(assembleium), params: { assembleium: new_attributes }
        assembleium.reload
        expect(response).to redirect_to(assembleium_url(assembleium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        assembleium = Assembleium.create! valid_attributes
        patch assembleium_url(assembleium), params: { assembleium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested assembleium" do
      assembleium = Assembleium.create! valid_attributes
      expect {
        delete assembleium_url(assembleium)
      }.to change(Assembleium, :count).by(-1)
    end

    it "redirects to the assembleia list" do
      assembleium = Assembleium.create! valid_attributes
      delete assembleium_url(assembleium)
      expect(response).to redirect_to(assembleia_url)
    end
  end
end
